### DISCUSSION TITLE
Mocap Coordinate Problem

### DISCUSSION THREAD

**Discussion by Lilezh** [USC-ACTLab/crazyswarm#530] [Q&A]
Hi, 

I want to implement a triangle formation control using three default crazyflies and an Optitrack (Motive 2.1) system. I am using ubuntu 20.04 and ROS noetic. I have tested helloworld.py. It seems pretty good. But I am facing some problems while testing the waypoints_simple.py.

1. First, I am confused how the coordinate actually looks like. The default y-axis is upward for the mocap system. Since we are setting the z-axis upward, **how does the other axis change? Will the x-axis keep the same? When we place the crazyflies, should they face the x-axis of the mocap system(y-axis up) or the x-axis of (z-axis up)?**

2. The position of the origin and crazyflies does not make sense. It seems that the position of the origin is not the origin of the mocap system. **Should the origin in the rviz match the origin of the mocap system?** The rostopic echo of /tf and /cf1/pose is matched with each other and the z-coordinate is correct but x,y is very weird. This is the situation I met: I placed the crazyflie at a random position checking /tf and /cf/pose. The value of them is always 0 (some values very close to 0) at first and the origin of the mocap system is never the origin in the rviz. **Is that normal?** Also, I did not change the position but the value of /tf and /cf/pose was changing gradually. And I can see that the axis of the rigid body in Motive sometimes will flip and shake. **Is this because of the bad arrangement of the markers?** 

3. Also, I check `rostopic hz /cf1/pose`. The weird thing is that the frequency is initially 9 and it suddenly drops to around 3 and sometimes no message.  

4. **The waypoints are the coordinate of the positions with respect to the origin of the mocap system or the crazyflie?** 

5. This is the previous arrangement of the markers. I add one more marker but does not fix the coordinate problem. Could you give me some ideas on how to arrange those markers and how many should I need? Can they be placed at the center of the mocap marker deck? Can I touch them since I heard that the coating of those markers is very sensitive?

![IMG_0021](https://user-images.githubusercontent.com/90261043/141922207-a97be25b-f7e9-4103-8d69-2402fa352456.jpg)

Thank you so much for your help.

**Comment by whoenig** [comment]
1. All what counts is the ROS coordinate system (z up). Unfortunately, this doesn't match what Motive shows, but you can use rviz to visualize it. It's a righthanded system with z up and x forward (where the antenna is).
2. Yes, the origins should match.
3. This is not normal, it should match the setting in Motive (typically 100 or 120 Hz).
4. Global coordinates, i.e., with respect to the origin.
5. Try to avoid symmetries. You can even fly with a single marker. Most markers aren't too sensitive to touch. The coating can wear off over time if you crash frequently, though.

Are you using "optitrack", or "optitrack_closed_source"? Avoid the "vrpn" mode, which might not map the optitrack -> ROS coordinate system correctly.

**Reply by Lilezh** [reply]
Thank you for your reply! I am using "optitrack" since I am using Motive 2.1.0, right? I remember someone said that the default logging frequency of /cf/pose is just 10 Hz? My Motive setting is using 60 Hz.

**Reply by whoenig** [reply]
Yes, "optitrack" is a good choice. For `/cf/pose`: you are right - my bad. The frequency of `tf` should match your Motive setting, but `cf/pose` is streamed over the radio. If you get a lower rate, that indicates that the radio is busy with other tasks (too many CFs/radio? other logging topics?).

**Reply by Lilezh** [reply]
As you can see, the pose keeps updating when the crazyflie does not move. And updating rate of both /tf and /pose are super low. 
````
ile@jarvis:~$ rostopic echo /cf1/pose 
header: 
  seq: 108
  stamp: 
    secs: 1637187778
    nsecs: 381352059
  frame_id: "world"
pose: 
  position: 
    x: -0.2324848175048828
    y: -0.18215312063694
    z: 0.016327138990163803
  orientation: 
    x: -0.0013837706064805388
    y: -0.012453935109078884
    z: 0.0013837706064805388
    w: 0.9999205470085144
---
............
header: 
  seq: 335
  stamp: 
    secs: 1637187857
    nsecs: 106514203
  frame_id: "world"
pose: 
  position: 
    x: -0.5403367280960083
    y: -0.4164201021194458
    z: 0.014546176418662071
  orientation: 
    x: -0.0027675412129610777
    y: -0.01107016485184431
    z: 0.0013837706064805388
    w: 0.9999338984489441
---
............
header: 
  seq: 627
  stamp: 
    secs: 1637187972
    nsecs: 213536274
  frame_id: "world"
pose: 
  position: 
    x: -1.4310050010681152
    y: -1.072557806968689
    z: 0.016137242317199707
  orientation: 
    x: -0.004151311703026295
    y: -0.013837706297636032
    z: 0.0013837706064805388
    w: 0.9998946785926819
---

````
````
lile@jarvis:~$ rostopic hz /tf
subscribed to [/tf]
no new messages
no new messages
no new messages
average rate: 2.424
	min: 0.100s max: 2.903s std dev: 0.88061s window: 10
no new messages
no new messages
no new messages
average rate: 1.733
	min: 0.100s max: 3.481s std dev: 1.12074s window: 14
average rate: 2.096
	min: 0.100s max: 3.481s std dev: 0.99739s window: 18
average rate: 2.247
	min: 0.100s max: 3.481s std dev: 0.88996s window: 23
average rate: 2.501
	min: 0.100s max: 3.481s std dev: 0.81071s window: 28
````
Also, I found that in the roslaunch crazyswarm hover_swarm.launch, it said that a lot of packets lost.
```
update ctrlMel/kp_z to 1.25
update ctrlMel/kw_xy to 20000
update ctrlMel/kw_z to 12000
update ctrlMel/mass to 0.032
update ctrlMel/massThrust to 132000
[ INFO] [1637187743.663797004]: [cf1] Update parameters
[ INFO] [1637187743.715906818]: [cf1] CONTROLLER: Using Mellinger (2) controller
[ INFO] [1637187743.744190189]: Update params: 0.087194 s
[ INFO] [1637187743.744449846]: Started 1 threads
[ INFO] [1637187797.768878883]: [cf1] WARNING: LOG packets drop detelost)
[ INFO] [1637187841.204053777]: [cf1] st)
[ INFO] [1637187909.080456662]: [cf1] : LOG packets drop detected (1d (2001 packets lost)
[ INFO] [1637187937.347489483]: [cf1]  (2101 packets lost)
[ INFO] [1637187945.054931018]: [cf1] s lost)
[ INFO] [1637187952.741671023]: [cf1] cted (2601 packets lost)
[ INFO] [1637187960.140170971]: [cf1] ost)
[ INFO] [1637187996.391470625]: [cf1] ts drop detected (2801 packetsdrop detected (1601 packets lo1 packets lost)
[ INFO] [1637188003.848156563]: [cf1] tected (3301 packets lost)
```

> If you get a lower rate, that indicates that the radio is busy with other tasks (too many CFs/radio? other logging topics?).


I think M4 light is flickering so the radio is connected. And my radio PA is quite close to the crazyflie. I just use one radio to control one CF. Is there any other ways to check how busy the radio is? This is my setting in hover_swarm.launch.

```
     # tracking
      motion_capture_type: "optitrack" # one of none,vicon,optitrack,qualisys,vrpn
      object_tracking_type: "motionCapture" # one of motionCapture,libobjecttracker
      send_position_only: False # set to False to send position+orientation; set to True to send position only
      motion_capture_host_name: "192.168.1.103"
      save_point_clouds: "/dev/null" # set to a valid path to log mocap point cloud binary file.
      print_latency: False
      write_csvs: False
      force_no_cache: False
      enable_parameters: True
      enable_logging: True
      enable_logging_pose: True
```
