### DISCUSSION TITLE
Flight instability

### DISCUSSION THREAD

**Discussion by SimpleMathmatics** [USC-ACTLab/crazyswarm#575] [Q&A] [answered]
Dear Hoenig, 

First of all, thank you for this awesome project! It is a lot of fun to work with. 

To our issue: 
We are experienceing flight instabilities when flying our crazyflies with crazyswarm. Specificially, some cfs start flying in circles and eventually crash, as it can be seen [here](https://youtu.be/M9RsNyAcYYE?t=36). 

To our setup: 
* We use a vicon vero motion capture system
* The cf version is 2.1
* We use single marker tracking
* All radios and cfs have the latest firmware installed

It would be highly appreciated if you could share your first thought, since we couldn't find out, what could be the issue here. 

Thank you very much! greetings from Austria, 
All the best, 
Julian

**Comment by whoenig** [comment]
Thanks for the detailed report! I think your problem is https://github.com/bitcraze/crazyflie-firmware/issues/870. If you apply the fix described there, re-compile, and re-flash the STM32 firmware it should work fine.

**Reply by SimpleMathmatics** [reply]
Dear @whoenig , 

Thank you for the fast answer, it sounds reasonable. Unfortunately I don't have access to the setup this year again, but I will update you first week next year if it worked :) 

Merry Christmas 
Julian

**Reply by SimpleMathmatics** [reply]
Dear @whoenig , 

As I had access to the setup yesterday, I followed your instructions: I pulled the latest updates from the cf firmware repo, deleted the two blocks of code as described [in the issue](https://github.com/bitcraze/crazyflie-firmware/issues/870), recompiled and flashed the firmware on the cfs. 

However, the issue persists (some cfs eventually fly in circles, even shortly after moving in x,y direction). I would be glad for every further suggestion on the cause... If any further information/data is needed, I will do my best to provide it. Latency looks good, however there are sometimes warnings on low link quality to some cfs (only in the beginning). 

Thank you in advance. 
BR, 
Julian

**Reply by whoenig** [reply]
Thanks for the update - too bad that the EKF change didn't work for you. I have a few more questions:

1. How many radios do you use?
2. Is logging enabled or disabled?
3. Does the problem only occur when flying all 9 robots, or also for smaller sizes?
4. Can you confirm that the drones essentially first track the wrong yaw angle, before they become unstable (hard to see on the video, but that was my first impression when I watched it). If that is the case, using the traditional 4-marker-tracking (with libObjectTracker for tracking) might help (depending on the mocap setup).

**Reply by SimpleMathmatics** [reply]
Thank you for your reply!

> How many radios do you use?

I just use a single radio. 

> Is logging enabled or disabled?

I had it enabled, but disabling did not change the problem. 

> Does the problem only occur when flying all 9 robots, or also for smaller sizes?

Yes, the problem also occurs, even when flying only a single cf. 

> Can you confirm that the drones essentially first track the wrong yaw angle, before they become unstable (hard to see on the video, but that was my first impression when I watched it). If that is the case, using the traditional 4-marker-tracking (with libObjectTracker for tracking) might help (depending on the mocap setup).

Yes, now that you mentioned it, it seems that the cfs track the wrong yaw angle (up to 45 degrees) long (~10-15s) before they become unstable. Unfortunatly, I couln't verify yet, if the problem is solved with 4-marker-tracking, as I couldn't find the cause for this error yet, that occurs when I try to switch to identical marker tracking: 

```
[ INFO] [1641382138.029547380]: waitForService: Service [/emergency] is now available.
[ INFO] [1641382138.032376116]: Manager ready.
[ INFO] [1641382138.038148109]: libmotioncapture connecting to vicon at hostname '192.168.10.1:801' - might block indefinitely if unreachable!
ch: 1
[ INFO] [1641382138.054136762]: Parsed crazyflies.yaml successfully.
[ INFO] [1641382138.054218776]: Adding CF: cf9 (radio://0/100/2M/E7E7E7E709, cf9)...
[ INFO] [1641382138.121583108]: CF ctor: 0.067289 s
[ WARN] [1641382138.123985333]: Received unrequested data for block: 0
[ INFO] [1641382138.127066493]: [cf9] ESTKALMAN: State out of bounds, resetting
[ INFO] [1641382138.130184731]: [cf9] ESTKALMAN: State out of bounds, resetting
[ INFO] [1641382138.133082523]: [cf9] , resetting
[ INFO] [1641382138.134678753]: [cf9] Requesting parameters...
[ INFO] [1641382138.143360196]: Found variables in cache.
[ INFO] [1641382138.523670504]: [cf9] reqParamTOC: 0.402012 s (232 params)
[ INFO] [1641382138.523720824]: [cf9] Requesting logging variables...
[ INFO] [1641382138.526401525]: Found variables in cache.
[ INFO] [1641382138.527439607]: [cf9] reqLogTOC: 0.003780 s
[ INFO] [1641382138.533329280]: [cf9] logBlocks: 0.402012 s
[ INFO] [1641382138.533445365]: Requesting memories...
[ INFO] [1641382138.536117508]: Memories: 4
[ INFO] [1641382138.545461722]: [cf9] Ready. Elapsed: 0.423799 s
[ INFO] [1641382138.545616902]: CF run: 0.424054 s
update commander/enHighLevel to 1
update kalman/resetEstimation to 1
update locSrv/extPosStdDev to 0.001
update locSrv/extQuatStdDev to 0.05
update ring/effect to 16
update ring/headlightEnable to 0
update ring/solidBlue to 255
update ring/solidGreen to 0
update ring/solidRed to 0
update stabilizer/controller to 2
update stabilizer/estimator to 2
update ctrlMel/i_range_m_z to 1500
update ctrlMel/i_range_xy to 2
update ctrlMel/i_range_z to 0.4
update ctrlMel/kR_xy to 70000
update ctrlMel/kR_z to 60000
update ctrlMel/kd_omega_rp to 200
update ctrlMel/kd_xy to 0.2
update ctrlMel/kd_z to 0.4
update ctrlMel/ki_m_z to 500
update ctrlMel/ki_xy to 0.05
update ctrlMel/ki_z to 0.05
update ctrlMel/kp_xy to 0.4
update ctrlMel/kp_z to 1.25
update ctrlMel/kw_xy to 20000
update ctrlMel/kw_z to 12000
update ctrlMel/mass to 0.032
update ctrlMel/massThrust to 132000
[ INFO] [1641382138.577235688]: [cf9] Update parameters
[ INFO] [1641382138.640783497]: Update params: 0.094789 s
[crazyswarm_server-2] process has died [pid 49959, exit code -11, cmd /home/ju/crazyswarm/ros_ws/devel/lib/crazyswarm/crazyswarm_server __name:=crazyswarm_server __log:=/home/ju/.ros/log/ab7b2218-6e1a-11ec-b49f-852e31509777/crazyswarm_server-2.log].
log file: /home/ju/.ros/log/ab7b2218-6e1a-11ec-b49f-852e31509777/crazyswarm_server-2*.log
```

any thoughts? Thank you, 

Julian

**Reply by whoenig** [reply]
The error indicates a segmentation fault. You would need to launch with a debugger to see where it is coming from. Perhaps you can also post any relevant changes to your config files (in particular `crazyflieTypes.yaml`), since those errors mostly occur after an incorrect configuration.

The issue what you are seeing is exactly what I was observing before the EKF change. I haven't tested the latest master-branch firmware, so maybe there are new EKF-related issues there. I tested with 2021.06, with my EKF fix applied.

**Reply by SimpleMathmatics** [reply]
> The error indicates a segmentation fault. You would need to launch with a debugger to see where it is coming from. 

Running it with gdb gives further information: 
```
Thread 8 "crazyswarm_serv" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffd7fff700 (LWP 60097)]
libobjecttracker::ObjectTracker::ObjectTracker (this=0x7fffcc01b300, 
    dynamicsConfigurations=..., markerConfigurations=..., objects=...)
    at /home/julianbialas/crazyswarm/ros_ws/src/externalDependencies/libobjecttracker/src/object_tracker.cpp:89
89	    size_t const objNpts = objMarkers->size();
``` 
Seems like the markers are incorrectly given? Here is my `crazyflieTypes.yaml`: 
``` yaml
crazyflieTypes:
  default:
    bigQuad: False
    batteryVoltageWarning: 3.8  # V
    batteryVoltateCritical: 3.7 # V
    markerConfiguration: 4 # change to 3 for single marker tracking
    dynamicsConfiguration: 0
    firmwareParams:
      ctrlMel:
        kp_xy: 0.4 #0.6 # p for position
        kd_xy: 0.2 # 0.35 # d for position
        ki_xy: 0.05
        i_range_xy: 2.0
        kR_xy: 70000 # p for attitude
        kw_xy: 20000 # d for attitude
        kR_z: 60000 # 70000 # p for yaw
        kw_z: 12000 # 30000  # d for yaw
        ki_m_z: 500 #0 #20000     # i for yaw
        i_range_m_z: 1500 # i range for yaw
        kd_omega_rp: 200 # roll and pitch angular velocity d gain
        kp_z: 1.25
        kd_z: 0.4
        ki_z: 0.05
        i_range_z: 0.4
        mass: 0.032
        massThrust: 132000
  defaultSingleMarker:
    bigQuad: False
    batteryVoltageWarning: 3.8  # V
    batteryVoltateCritical: 3.7 # V
    markerConfiguration: 3 # changed to 3 for single marker tracking
    dynamicsConfiguration: 0
    firmwareParams:
      kalman:
        pNAcc_xy: 4.0 # default 0.5
        pNAcc_z: 8.0 # default 1.0
        mNGyro_rollpitch: 0.2 # default 0.1
        mNGyro_yaw: 0.1 # default 0.1
      ctrlMel:
        kp_xy: 0.4 #0.6 # p for position
        kd_xy: 0.2 # 0.35 # d for position
        ki_xy: 0.05
        i_range_xy: 2.0
        kR_xy: 70000 # p for attitude
        kw_xy: 20000 # d for attitude
        kR_z: 60000 # 70000 # p for yaw
        kw_z: 12000 # 30000  # d for yaw
        ki_m_z: 500 #0 #20000     # i for yaw
        i_range_m_z: 1500 # i range for yaw
        kd_omega_rp: 200 # roll and pitch angular velocity d gain
        kp_z: 1.25
        kd_z: 0.4
        ki_z: 0.05
        i_range_z: 0.4
        mass: 0.032
        massThrust: 132000
  CF21SingleMarker:
    bigQuad: False
    batteryVoltageWarning: 3.8  # V
    batteryVoltateCritical: 3.7 # V
    markerConfiguration: 3 # changed to 3 for single marker tracking
    dynamicsConfiguration: 0
    firmwareParams:
      kalman:
        pNAcc_xy: 1.0 # default 0.5
        pNAcc_z: 2.0 # default 1.0
        mNGyro_rollpitch: 0.1 # default 0.1
        mNGyro_yaw: 0.1 # default 0.1
      ctrlMel:
        kp_xy: 0.4 #0.6 # p for position
        kd_xy: 0.2 # 0.35 # d for position
        ki_xy: 0.05
        i_range_xy: 2.0
        kR_xy: 70000 # p for attitude
        kw_xy: 20000 # d for attitude
        kR_z: 60000 # 70000 # p for yaw
        kw_z: 12000 # 30000  # d for yaw
        ki_m_z: 500 #0 #20000     # i for yaw
        i_range_m_z: 1500 # i range for yaw
        kd_omega_rp: 200 # roll and pitch angular velocity d gain
        kp_z: 1.25
        kd_z: 0.4
        ki_z: 0.05
        i_range_z: 0.4
        mass: 0.032
        massThrust: 132000
  medium:
    bigQuad: True
    batteryVoltageWarning: 7.6  # V
    batteryVoltateCritical: 7.4 # V
    markerConfiguration: 1
    dynamicsConfiguration: 0
    firmwareParams:
      ctrlMel:
        kp_xy: 2.0 # p for position
        kd_xy: 1.0 # d for position
        ki_xy: 0.1 # i for position
        i_range_xy: 2.0 # range for position
        kR_xy: 50000 # 50000 # p for attitude
        kw_xy: 16000 # 16000 # d for attitude
        kR_z: 60000 # p for yaw
        kw_z: 12000 # d for yaw
        ki_m_z: 500 # i for yaw
        i_range_m_z: 1500 # i range for yaw
        kd_omega_rp: 200 # roll and pitch angular velocity d gain
        kp_z: 3 # 1.25
        kd_z: 1.0
        ki_z: 0.5 # 0.05
        i_range_z: 2.0
        mass: 0.110
        massThrust: 23000 # 23000 - full battery
  large:
    bigQuad: True
    batteryVoltageWarning: 11.4  # V
    batteryVoltateCritical: 11.1 # V
    markerConfiguration: 2
    dynamicsConfiguration: 0
    firmwareParams:
      ctrlMel:
        kp_xy: 8.0 # 0.4 #0.6 # p for position
        kd_xy: 3.0 # 0.2 # 0.35 # d for position
        ki_xy: 1.0 # 0.05
        i_range_xy: 2.0
        kR_xy: 30000 # 40000 # p for attitude
        kw_xy: 9000 # 13000 # d for attitude
        kR_z: 40000 # 70000 # p for yaw
        kw_z: 10000 # 30000  # d for yaw
        ki_m_z: 500 #0 #20000     # i for yaw
        i_range_m_z: 1500 # i range for yaw
        kd_omega_rp: 100 # roll and pitch angular velocity d gain
        kp_z: 8.0 # 1.25
        kd_z: 3.0 # 0.4
        ki_z: 2.0 # 0.05
        i_range_z: 4.0
        mass: 0.380
        massThrust: 5400 # 5500 - full battery
numMarkerConfigurations: 4
markerConfigurations:
  "0":  # for standard Crazyflie
    numPoints: 4
    offset: [0.0, -0.01, -0.04]
    points:
      "0": [0.0177184,0.0139654,0.0557585]
      "1": [-0.0262914,0.0509139,0.0402475]
      "2": [-0.0328889,-0.02757,0.0390601]
      "3": [0.0431307,-0.0331216,0.0388839]
  "1": # medium frame
    numPoints: 4
    offset: [0.0, 0.0, -0.03]
    points:
      "0": [-0.00896228,-0.000716753,0.0716129]
      "1": [-0.0156318,0.0997402,0.0508162]
      "2": [0.0461693,-0.0881012,0.0380672]
      "3": [-0.0789959,-0.0269793,0.0461144]
  "2": # big frame
    numPoints: 4
    offset: [0.0, 0.0, -0.06]
    points:
      "0": [0.0558163,-0.00196302,0.0945539]
      "1": [-0.0113941,0.00945842,0.0984811]
      "2": [-0.0306277,0.0514879,0.0520456]
      "3": [0.0535816,-0.0400775,0.0432799]

  "3":  # for standard Crazyflie with a single marker
    numPoints: 1
    offset: [0.0, -0.01, -0.04]
    points:
      "0": [0.0177184,0.0139654,0.0557585]

  "4": # for a marker on each arm
    numPoints: 4
    offset: [0.0, -0.01, -0.04]
    points: # extracted from mocap_helper after putting the cf on origin
      "0": [-0.0181716,-0.00531236,0.0200703]
      "1": [0.0249426,0.0365873,0.0210529]
      "2": [-0.0191327,0.038892,0.0205276]
      "3": [0.0239294,-0.00594741,0.0209519]
``` 

and my `crazyflies.yaml` (only using the cf9 for now, since this cf seem to always show the problem (even if it has the same firmware as the others): 

```yaml
crazyflies:
- channel: 100
  id: 9
  initialPosition:
  - -1.0
  - -1.0
  - 0.0
  type: default
```

> The issue what you are seeing is exactly what I was observing before the EKF change. I haven't tested the latest master-branch firmware, so maybe there are new EKF-related issues there. I tested with 2021.06, with my EKF fix applied.

I have recompiled the firmware with release 2021.06 (latest commit a096b49), however, the problem still occurs. 
Thank you for your help! 
Julian
