### DISCUSSION TITLE
Using Multiple CFs

### DISCUSSION THREAD

**Discussion by GideonLombardo** [USC-ACTLab/crazyswarm#633] [Q&A] [answered]
Hello

As most of you have seen, I have been in the process of configuring my Crazyswarm system. I have gotten stable hovering flight with a single CF. I am now moving on to using multiple CFs in my research. I have defined a new CF in my Crazyswarm system and in the Vicon system which I use for motion capture. I use unique marker configurations in my research. The crazyswarm server will not track both CFs for some reason. 

I receive the following error:
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  No matching USB Device with devid = 1 found! Do you have a Crazyradio dongle connected?
```
This issue is fixed when I stop tracking one of the CFs in Vicon. However, I need to be able to track multiple CFs for my research. 

Here are my yaml files:

crazyflies.yaml:

```
crazyflies:
- channel: 80
  id: 5
  initialPosition:
  - 1.5
  - 1.5
  - 0.0
  type: medium
- channel: 90
  id: 6
  initial Position:
  - -1.0
  - -0.5
  - 0.0
  type: medium

```

allCrazyflies.yaml:

```
crazyflies:
  - id: 5
    channel: 80
    initialPosition: [1.5, 1.5, 0.0]
    type: medium
  - id: 6
    channel: 90
    initialPosition: [-1.0, -0.5, 0.0]
    type: medium
```

And a picture of my chooser is attached.

![Screenshot from 2022-04-18 20-35-14](https://user-images.githubusercontent.com/99747644/163902780-16678ba9-5859-4da7-a324-9e6467dbdd17.png)

I am concerned that there is something wrong my Crazyradio, but I followed the documentation to flash the latest firmware.

Does anyone have any suggestions? Please let me know.
