### DISCUSSION TITLE
Communication Problem: A node is grayed out and disappears

### DISCUSSION THREAD

**Discussion by sAz-G** [USC-ACTLab/crazyswarm#674] [Q&A]
Hi everyone, 

I have a problem using more than 2 drones on the crazyswarm platform.

When I try to connect to three or more drones, one disappears from the rviz gui (see figures).
![fig1](https://user-images.githubusercontent.com/66619540/184160789-4fb8117f-c113-4a8f-85e3-24885c21e7ae.png)
![fig2](https://user-images.githubusercontent.com/66619540/184160796-bcec5d7a-a441-498e-b1eb-79b45ded3eb5.png)

The above figures show two different scenarios for two different configurations of the crazyflies.yaml file. See configurations below:

### conf 1

Here cf6 disappears 

```
crazyflies:
- channel: 80
  id: 6
  initialPosition:
  - 1.5
  - 1.5
  - 0.0
  type: default
- channel: 80
  id: 2
  initialPosition:
  - -1.0
  - -0.5
  - 0.0
  type: default
- channel: 80
  id: 1
  initialPosition:
  - -1.0
  - -0.5
  - 0.0
  type: default
```

### conf 2

Here cf1 disappears 
 
```
crazyflies:
- channel: 80
  id: 1
  initialPosition:
  - 1.5
  - 1.5
  - 0.0
  type: default
- channel: 80
  id: 2
  initialPosition:
  - -1.0
  - -0.5
  - 0.0
  type: default
- channel: 80
  id: 6
  initialPosition:
  - -1.0
  - -0.5
  - 0.0
  type: default
```

This problem occurs with a fresh install of the crazyswarm platform and the crazyflie firmware, but also with an already used and modified install, where this problem newly occurred.

Does anybody have an idea what can I try to solve this?
