### DISCUSSION TITLE
Unable to launch chooser.py

### DISCUSSION THREAD

**Discussion by darshit-desai** [USC-ACTLab/crazyswarm#754] [Q&A]
# Error Description
I am doing the initial setup and configuration for crazyswarm 1.0 and the problem is that it is unable to launch the chooser.py program.
The terminal output is shown below
### Bash terminal output
```bash
darshit@darshit-Inspiron-5558:~/crazyswarm/ros_ws/src/crazyswarm/scripts$ python3 chooser.py
WARNING: Could not find STM32 firmware (/home/darshit/crazyswarm/ros_ws/src/crazyswarm/scripts/../../../../crazyflie-firmware/cf2.bin).
WARNING: Could not find NRF51 firmware (/home/darshit/crazyswarm/ros_ws/src/crazyswarm/scripts/../../../../crazyflie2-nrf-firmware/cf2_nrf.bin).
Traceback (most recent call last):
  File "chooser.py", line 63, in <module>
    allCrazyflies = read_by_id(os.path.join(args.configpath, "allCrazyflies.yaml"))
  File "chooser.py", line 48, in read_by_id
    root = yaml.load(ymlfile)
TypeError: load() missing 1 required positional argument: 'Loader'
```

# YAML, launch, cfclient id definition:
Here's some relevant configuration data and the defined id screenshot:

## cfclient radio id screenshot:
The radio id is defined as radio://0/80/2M/E7E7E7E701, (as shown in the photo below same appears in the scan search)
![image](https://github.com/USC-ACTLab/crazyswarm/assets/36150235/4e13c6d2-6ad1-4a89-abb2-28ae68100bdc)

## hover_swarm.launch
```XML
<?xml version="1.0"?>
<launch>
  <arg name="joy_dev" default="/dev/input/js0" />

  <rosparam command="load" file="$(find crazyswarm)/launch/crazyflieTypes.yaml" />
  <rosparam command="load" file="$(find crazyswarm)/launch/crazyflies.yaml" />

  <node pkg="crazyswarm" type="crazyswarm_server" name="crazyswarm_server" output="screen" >
    <rosparam>
      # Logging configuration (Use enable_logging to actually enable logging)
      genericLogTopics: ["log1"]
      genericLogTopicFrequencies: [10]
      genericLogTopic_log1_Variables: ["stateEstimate.x", "ctrltarget.x"]
      # firmware parameters for all drones (use crazyflieTypes.yaml to set per type, or
      # allCrazyflies.yaml to set per drone)
      firmwareParams:
        commander:
          enHighLevel: 1
        stabilizer:
          estimator: 2 # 1: complementary, 2: kalman
          controller: 2 # 1: PID, 2: mellinger
        ring:
          effect: 16 # 6: double spinner, 7: solid color, 16: packetRate
          solidBlue: 255 # if set to solid color
          solidGreen: 0 # if set to solid color
          solidRed: 0 # if set to solid color
          headlightEnable: 0
        locSrv:
          extPosStdDev: 1e-3
          extQuatStdDev: 0.5e-1
        kalman:
          resetEstimation: 1
      # tracking
      motion_capture_type: "vicon" # one of none,vicon,optitrack,optitrack_closed_source,qualisys,vrpn
      object_tracking_type: "libobjecttracker" # one of motionCapture,libobjecttracker
      send_position_only: False # set to False to send position+orientation; set to True to send position only
      motion_capture_host_name: "192.168.78.11"
      # motion_capture_interface_ip: "" # optional for optitrack with multiple interfaces
      save_point_clouds: "/dev/null" # set to a valid path to log mocap point cloud binary file.
      print_latency: False
      write_csvs: False
      force_no_cache: False
      enable_parameters: True
      enable_logging: False
      enable_logging_pose: True
    </rosparam>
  </node>

  <node name="joy" pkg="joy" type="joy_node" output="screen">
    <param name="dev" value="$(arg joy_dev)" />
  </node>

  <node pkg="crazyswarm" type="crazyswarm_teleop" name="crazyswarm_teleop" output="screen">
    <param name="csv_file" value="$(find crazyswarm)/launch/figure8_smooth.csv" />
    <param name="timescale" value="0.8" />
  </node>

  <node name="rviz" pkg="rviz" type="rviz" args="-d $(find crazyswarm)/launch/test.rviz"/>

  <!-- <node pkg="rqt_plot" type="rqt_plot" name="rqt_plot_x" args="/cf2/log1/values[0]"/> -->
  <!-- <node pkg="rqt_plot" type="rqt_plot" name="rqt_plot_roll" args="/cf1/log1/values[2] /cf1/log1/values[3]"/> -->

</launch>

```
## crazyflies.yaml
```YAML

crazyflies:
- channel: 80
  id: 1
  initialPosition: [0.0, 0.0, 0.0]
  type: defaultSingleMarker
```
## allcrazyflies.yaml
```YAML

crazyflies:
  - id: 1
    channel: 80
    initialPosition: [0.0, 0.0, 0.0]
    type: defaultSingleMarker
```
## crazyflietypes.yaml
```YAML
crazyflieTypes:
  default:
    bigQuad: False
    batteryVoltageWarning: 3.8  # V
    batteryVoltateCritical: 3.7 # V
    markerConfiguration: 0 # change to 3 for single marker tracking
    dynamicsConfiguration: 0
    firmwareParams:
      ctrlMel:
        kp_xy: 0.4 #0.6 # p for position
        kd_xy: 0.2 # 0.35 # d for position
        ki_xy: 0.05
        i_range_xy: 2.0
        kR_xy: 70000 # p for attitude
        kw_xy: 20000 # d for attitude
        kR_z: 60000 # 70000 # p for yaw
        kw_z: 12000 # 30000  # d for yaw
        ki_m_z: 500 #0 #20000     # i for yaw
        i_range_m_z: 1500 # i range for yaw
        kd_omega_rp: 200 # roll and pitch angular velocity d gain
        kp_z: 1.25
        kd_z: 0.4
        ki_z: 0.05
        i_range_z: 0.4
        mass: 0.032
        massThrust: 132000
  defaultSingleMarker:
    bigQuad: False
    batteryVoltageWarning: 3.8  # V
    batteryVoltateCritical: 3.7 # V
    markerConfiguration: 3 # changed to 3 for single marker tracking
    dynamicsConfiguration: 0
    firmwareParams:
      kalman:
        pNAcc_xy: 4.0 # default 0.5
        pNAcc_z: 8.0 # default 1.0
        mNGyro_rollpitch: 0.2 # default 0.1
        mNGyro_yaw: 0.1 # default 0.1
      ctrlMel:
        kp_xy: 0.4 #0.6 # p for position
        kd_xy: 0.2 # 0.35 # d for position
        ki_xy: 0.05
        i_range_xy: 2.0
        kR_xy: 70000 # p for attitude
        kw_xy: 20000 # d for attitude
        kR_z: 60000 # 70000 # p for yaw
        kw_z: 12000 # 30000  # d for yaw
        ki_m_z: 500 #0 #20000     # i for yaw
        i_range_m_z: 1500 # i range for yaw
        kd_omega_rp: 200 # roll and pitch angular velocity d gain
        kp_z: 1.25
        kd_z: 0.4
        ki_z: 0.05
        i_range_z: 0.4
        mass: 0.032
        massThrust: 132000
  CF21SingleMarker:
    bigQuad: False
    batteryVoltageWarning: 3.8  # V
    batteryVoltateCritical: 3.7 # V
    markerConfiguration: 3 # changed to 3 for single marker tracking
    dynamicsConfiguration: 0
    firmwareParams:
      kalman:
        pNAcc_xy: 1.0 # default 0.5
        pNAcc_z: 2.0 # default 1.0
        mNGyro_rollpitch: 0.1 # default 0.1
        mNGyro_yaw: 0.1 # default 0.1
      ctrlMel:
        kp_xy: 0.4 #0.6 # p for position
        kd_xy: 0.2 # 0.35 # d for position
        ki_xy: 0.05
        i_range_xy: 2.0
        kR_xy: 70000 # p for attitude
        kw_xy: 20000 # d for attitude
        kR_z: 60000 # 70000 # p for yaw
        kw_z: 12000 # 30000  # d for yaw
        ki_m_z: 500 #0 #20000     # i for yaw
        i_range_m_z: 1500 # i range for yaw
        kd_omega_rp: 200 # roll and pitch angular velocity d gain
        kp_z: 1.25
        kd_z: 0.4
        ki_z: 0.05
        i_range_z: 0.4
        mass: 0.032
        massThrust: 132000
  medium:
    bigQuad: True
    batteryVoltageWarning: 7.6  # V
    batteryVoltateCritical: 7.4 # V
    markerConfiguration: 1
    dynamicsConfiguration: 0
    firmwareParams:
      ctrlMel:
        kp_xy: 2.0 # p for position
        kd_xy: 1.0 # d for position
        ki_xy: 0.1 # i for position
        i_range_xy: 2.0 # range for position
        kR_xy: 50000 # 50000 # p for attitude
        kw_xy: 16000 # 16000 # d for attitude
        kR_z: 60000 # p for yaw
        kw_z: 12000 # d for yaw
        ki_m_z: 500 # i for yaw
        i_range_m_z: 1500 # i range for yaw
        kd_omega_rp: 200 # roll and pitch angular velocity d gain
        kp_z: 3 # 1.25
        kd_z: 1.0
        ki_z: 0.5 # 0.05
        i_range_z: 2.0
        mass: 0.110
        massThrust: 23000 # 23000 - full battery
  large:
    bigQuad: True
    batteryVoltageWarning: 11.4  # V
    batteryVoltateCritical: 11.1 # V
    markerConfiguration: 2
    dynamicsConfiguration: 0
    firmwareParams:
      ctrlMel:
        kp_xy: 8.0 # 0.4 #0.6 # p for position
        kd_xy: 3.0 # 0.2 # 0.35 # d for position
        ki_xy: 1.0 # 0.05
        i_range_xy: 2.0
        kR_xy: 30000 # 40000 # p for attitude
        kw_xy: 9000 # 13000 # d for attitude
        kR_z: 40000 # 70000 # p for yaw
        kw_z: 10000 # 30000  # d for yaw
        ki_m_z: 500 #0 #20000     # i for yaw
        i_range_m_z: 1500 # i range for yaw
        kd_omega_rp: 100 # roll and pitch angular velocity d gain
        kp_z: 8.0 # 1.25
        kd_z: 3.0 # 0.4
        ki_z: 2.0 # 0.05
        i_range_z: 4.0
        mass: 0.380
        massThrust: 5400 # 5500 - full battery
numMarkerConfigurations: 4
markerConfigurations:
  "0":  # for standard Crazyflie
    numPoints: 4
    offset: [0.0, -0.01, -0.04]
    points:
      "0": [0.0177184,0.0139654,0.0557585]
      "1": [-0.0262914,0.0509139,0.0402475]
      "2": [-0.0328889,-0.02757,0.0390601]
      "3": [0.0431307,-0.0331216,0.0388839]
  "1": # medium frame
    numPoints: 4
    offset: [0.0, 0.0, -0.03]
    points:
      "0": [-0.00896228,-0.000716753,0.0716129]
      "1": [-0.0156318,0.0997402,0.0508162]
      "2": [0.0461693,-0.0881012,0.0380672]
      "3": [-0.0789959,-0.0269793,0.0461144]
  "2": # big frame
    numPoints: 4
    offset: [0.0, 0.0, -0.06]
    points:
      "0": [0.0558163,-0.00196302,0.0945539]
      "1": [-0.0113941,0.00945842,0.0984811]
      "2": [-0.0306277,0.0514879,0.0520456]
      "3": [0.0535816,-0.0400775,0.0432799]
  "3":  # for standard Crazyflie with a single marker
    numPoints: 1
    offset: [0.0, -0.01, -0.04]
    points:
      "0": [0.0177184,0.0139654,0.0557585]
numDynamicsConfigurations: 1
dynamicsConfigurations:
  "0":
    maxXVelocity: 2.0
    maxYVelocity: 2.0
    maxZVelocity: 3.0
    maxPitchRate: 20.0
    maxRollRate: 20.0
    maxYawRate: 10.0
    maxRoll: 1.4
    maxPitch: 1.4
    maxFitnessScore: 0.001


```
