### DISCUSSION TITLE
CF drone flips after launching the hello_world script

### DISCUSSION THREAD

**Discussion by darshit-desai** [USC-ACTLab/crazyswarm#755] [Q&A]
# Update with Flight video and screen video in single marker configuration 
@whoenig Just wanted to give an update on the exhaustive testing I did today with both CSW1 and CSW2, It is really weird that it takesoff easily but during hover the drone flips,

## Video Links and setup photo and video links:
Here are the videos and the screen capture of the terminal and rviz screens, Not really sure what is wrong here? (Sorry the videos were too large to upload here)

* CSW1 flight and screen capture videos: https://drive.google.com/drive/folders/1XPqn6w5M7P3lHvagQT0iIsTFmhQFdR44?usp=sharing
* CSW1&2 vicon setup video and drone photos: https://drive.google.com/drive/folders/1-kkjZqGGOITFE3EFHd4nGYxlFz0s2IEg?usp=sharing

### crazyflies.yaml
```YAML
crazyflies:
- channel: 80
  id: 1
  initialPosition:
  - 0.0
  - 0.0
  - 0.0
  type: CF21SingleMarker
```

### allCrazyflies.yaml
```YAML
crazyflies:
  - id: 1
    channel: 80
    initialPosition: [0.0, 0.0, 0.0]
    type: CF21SingleMarker
```
### crazyflieTypes.yaml (Tried to modify it for mocap deck but it's worse than the single marker config)
```YAML
crazyflieTypes:
  default:
    bigQuad: False
    batteryVoltageWarning: 3.8  # V
    batteryVoltateCritical: 3.7 # V
    markerConfiguration: 0 # change to 3 for single marker tracking
    dynamicsConfiguration: 0
    firmwareParams:
      ctrlMel:
        kp_xy: 0.4 #0.6 # p for position
        kd_xy: 0.2 # 0.35 # d for position
        ki_xy: 0.05
        i_range_xy: 2.0
        kR_xy: 70000 # p for attitude
        kw_xy: 20000 # d for attitude
        kR_z: 60000 # 70000 # p for yaw
        kw_z: 12000 # 30000  # d for yaw
        ki_m_z: 500 #0 #20000     # i for yaw
        i_range_m_z: 1500 # i range for yaw
        kd_omega_rp: 200 # roll and pitch angular velocity d gain
        kp_z: 1.25
        kd_z: 0.4
        ki_z: 0.05
        i_range_z: 0.4
        mass: 0.032
        massThrust: 132000
  defaultSingleMarker:
    bigQuad: False
    batteryVoltageWarning: 3.8  # V
    batteryVoltateCritical: 3.7 # V
    markerConfiguration: 3 # changed to 3 for single marker tracking
    dynamicsConfiguration: 0
    firmwareParams:
      kalman:
        pNAcc_xy: 4.0 # default 0.5
        pNAcc_z: 8.0 # default 1.0
        mNGyro_rollpitch: 0.2 # default 0.1
        mNGyro_yaw: 0.1 # default 0.1
      ctrlMel:
        kp_xy: 0.4 #0.6 # p for position
        kd_xy: 0.2 # 0.35 # d for position
        ki_xy: 0.05
        i_range_xy: 2.0
        kR_xy: 70000 # p for attitude
        kw_xy: 20000 # d for attitude
        kR_z: 60000 # 70000 # p for yaw
        kw_z: 12000 # 30000  # d for yaw
        ki_m_z: 500 #0 #20000     # i for yaw
        i_range_m_z: 1500 # i range for yaw
        kd_omega_rp: 200 # roll and pitch angular velocity d gain
        kp_z: 1.25
        kd_z: 0.4
        ki_z: 0.05
        i_range_z: 0.4
        mass: 0.032
        massThrust: 132000
  CF21SingleMarker:
    bigQuad: False
    batteryVoltageWarning: 3.8  # V
    batteryVoltateCritical: 3.7 # V
    markerConfiguration: 3 # changed to 3 for single marker tracking
    dynamicsConfiguration: 0
    firmwareParams:
      kalman:
        pNAcc_xy: 1.0 # default 0.5
        pNAcc_z: 2.0 # default 1.0
        mNGyro_rollpitch: 0.1 # default 0.1
        mNGyro_yaw: 0.1 # default 0.1
      ctrlMel:
        kp_xy: 0.4 #0.6 # p for position
        kd_xy: 0.2 # 0.35 # d for position
        ki_xy: 0.05
        i_range_xy: 2.0
        kR_xy: 70000 # p for attitude
        kw_xy: 20000 # d for attitude
        kR_z: 60000 # 70000 # p for yaw
        kw_z: 12000 # 30000  # d for yaw
        ki_m_z: 500 #0 #20000     # i for yaw
        i_range_m_z: 1500 # i range for yaw
        kd_omega_rp: 200 # roll and pitch angular velocity d gain
        kp_z: 1.25
        kd_z: 0.4
        ki_z: 0.05
        i_range_z: 0.4
        mass: 0.032
        massThrust: 132000
  medium:
    bigQuad: True
    batteryVoltageWarning: 7.6  # V
    batteryVoltateCritical: 7.4 # V
    markerConfiguration: 1
    dynamicsConfiguration: 0
    firmwareParams:
      ctrlMel:
        kp_xy: 2.0 # p for position
        kd_xy: 1.0 # d for position
        ki_xy: 0.1 # i for position
        i_range_xy: 2.0 # range for position
        kR_xy: 50000 # 50000 # p for attitude
        kw_xy: 16000 # 16000 # d for attitude
        kR_z: 60000 # p for yaw
        kw_z: 12000 # d for yaw
        ki_m_z: 500 # i for yaw
        i_range_m_z: 1500 # i range for yaw
        kd_omega_rp: 200 # roll and pitch angular velocity d gain
        kp_z: 3 # 1.25
        kd_z: 1.0
        ki_z: 0.5 # 0.05
        i_range_z: 2.0
        mass: 0.110
        massThrust: 23000 # 23000 - full battery
  large:
    bigQuad: True
    batteryVoltageWarning: 11.4  # V
    batteryVoltateCritical: 11.1 # V
    markerConfiguration: 2
    dynamicsConfiguration: 0
    firmwareParams:
      ctrlMel:
        kp_xy: 8.0 # 0.4 #0.6 # p for position
        kd_xy: 3.0 # 0.2 # 0.35 # d for position
        ki_xy: 1.0 # 0.05
        i_range_xy: 2.0
        kR_xy: 30000 # 40000 # p for attitude
        kw_xy: 9000 # 13000 # d for attitude
        kR_z: 40000 # 70000 # p for yaw
        kw_z: 10000 # 30000  # d for yaw
        ki_m_z: 500 #0 #20000     # i for yaw
        i_range_m_z: 1500 # i range for yaw
        kd_omega_rp: 100 # roll and pitch angular velocity d gain
        kp_z: 8.0 # 1.25
        kd_z: 3.0 # 0.4
        ki_z: 2.0 # 0.05
        i_range_z: 4.0
        mass: 0.380
        massThrust: 5400 # 5500 - full battery
numMarkerConfigurations: 4
markerConfigurations:
  "0":  # for standard Crazyflie
    numPoints: 4
    offset: [0.0, -0.01, -0.04]
    points:
      # "0": [0.0177184,0.0139654,0.0557585]
      # "1": [-0.0262914,0.0509139,0.0402475]
      # "2": [-0.0328889,-0.02757,0.0390601]
      # "3": [0.0431307,-0.0331216,0.0388839]
      "0": [0.0111499,-0.0331532,0.00175325]
      "1": [-0.0216291,-0.00582988,0.000635939]
      "2": [0.0136652,-0.0126833,0.00377512]
      "3": [0.00743287,0.00147324,0.00391192]
  "1": # medium frame
    numPoints: 4
    offset: [0.0, 0.0, -0.03]
    points:
      "0": [-0.00896228,-0.000716753,0.0716129]
      "1": [-0.0156318,0.0997402,0.0508162]
      "2": [0.0461693,-0.0881012,0.0380672]
      "3": [-0.0789959,-0.0269793,0.0461144]
      # "0": [0.0112149,-0.0331869,0.00173738]
      # "1": [0.00754326,0.00151631,0.00388856]
      # "2": [-0.0214196,-0.00603277,0.00108297]
      # "3": [0.0136738,-0.0127391,0.00383757]
  "2": # big frame
    numPoints: 4
    offset: [0.0, 0.0, -0.06]
    points:
      "0": [0.0558163,-0.00196302,0.0945539]
      "1": [-0.0113941,0.00945842,0.0984811]
      "2": [-0.0306277,0.0514879,0.0520456]
      "3": [0.0535816,-0.0400775,0.0432799]
  "3":  # for standard Crazyflie with a single marker
    numPoints: 1
    offset: [0.0, -0.01, -0.04]
    points:
      "0": [0.0177184,0.0139654,0.0557585]
numDynamicsConfigurations: 1
dynamicsConfigurations:
  "0":
    maxXVelocity: 2.0
    maxYVelocity: 2.0
    maxZVelocity: 3.0
    maxPitchRate: 20.0
    maxRollRate: 20.0
    maxYawRate: 10.0
    maxRoll: 1.4
    maxPitch: 1.4
    maxFitnessScore: 0.001

```
