### DISCUSSION TITLE
ESTKALMAN: State out of bounds, resetting,TF error

### DISCUSSION THREAD

**Discussion by ddwy** [USC-ACTLab/crazyswarm#757] [Q&A]
I have two CFs with Loco Positioning Deck,cf1,cf2.
I select the `motion_capture_type" to be "None".
In my launch file, set enable_logging and enable_logging_pose both to True.

crazyflie.yaml
```
crazyflies:
- channel: 80
  id: 1
  initialPosition:
  - 1.5
  - 1.5
  - 0.0
  type: default
- channel: 80
  id: 2
  initialPosition:
  - 1.5
  - 1.0
  - 0.0
  type: default
```

When I launch the hover_swarm.launch, it will print the following statement:ESTKALMAN: State out of bounds, resetting.And the TF displayed by rviz jumps back and forth.

hello_world.py can only control a single crazyflie, how can I control multiple drones?
