### ISSUE TITLE
hover_swarm.launch error

### ISSUE THREAD

**Issue by srnetsr** [USC-ACTLab/crazyswarm#45]
Hi, I am trying to integrate crazyswarm package with optitrack,
and I have some questions..

1. What do you mean that "**Un-tick the rigid body in Motive so that the point cloud is streamed.**" in [http://crazyswarm.readthedocs.io/en/latest/usage.html](link)

2. When I run `$ roslaunch crazyswarm hover_swarm.launch`, I found some errors.
**(1)** **`NatNetClient connecting: 130.**.***.251 to 130.**.***.237...Could not bind socket. Error: 99`**
The ip address is all correct, and I attach a part of launch file in regard with position capture system.
```
# tracking
      motion_capture_type: "optitrack" # one of vicon,optitrack
      object_tracking_type: "motionCapture" # one of motionCapture,libobjecttracker
      # vicon_host_name: "vicon"
      optitrack_local_ip: "130.**.***.251"
      optitrack_server_ip: "130.**.***.237"
      save_point_clouds: ~/pointCloud.ot
      # interactive_object: active-wand # virtual #active-wand
      numMarkerConfigurations: 1
      markerConfigurations:
        "0":
          numPoints: 4
          offset: [0.0, -0.01, -0.04]
          points:
            "0": [0.0177184,0.0139654,0.0557585]
            "1": [-0.0262914,0.0509139,0.0402475]
            "2": [-0.0328889,-0.02757,0.0390601]
            "3": [0.0431307,-0.0331216,0.0388839]
```

**(2)** Another one is the following error message. Could you help me to resolve this issue?
**"`[crazyflie_server-2] process has died [pid 17552, exit code 1, cmd /home/ubuntu/crazyswarm/ros_ws/devel/lib/crazyflie_driver/crazyflie_server __name:=crazyflie_server __log:=/home/ubuntu/.ros/log/01bf0fe8-0ec2-11e8-bc02-74d435137038/crazyflie_server-2.log]."`**
I attach the full message I saw.
```
... logging to /home/ubuntu/.ros/log/02888ffe-0ec1-11e8-bc02-74d435137038/roslaunch-ubuntu-17119.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://ubuntu:33309/

SUMMARY
========

PARAMETERS
 * /crazyflie_manager/csv_file: /home/ubuntu...
 * /crazyflie_manager/timescale: 0.8
 * /crazyflie_server/broadcast_address: FFE7E7E7E7
 * /crazyflie_server/dynamicsConfigurations/0/maxFitnessScore: 0.001
 * /crazyflie_server/dynamicsConfigurations/0/maxPitch: 1.4
 * /crazyflie_server/dynamicsConfigurations/0/maxPitchRate: 20.0
 * /crazyflie_server/dynamicsConfigurations/0/maxRoll: 1.4
 * /crazyflie_server/dynamicsConfigurations/0/maxRollRate: 20.0
 * /crazyflie_server/dynamicsConfigurations/0/maxXVelocity: 2.0
 * /crazyflie_server/dynamicsConfigurations/0/maxYVelocity: 2.0
 * /crazyflie_server/dynamicsConfigurations/0/maxYawRate: 10.0
 * /crazyflie_server/dynamicsConfigurations/0/maxZVelocity: 3.0
 * /crazyflie_server/enable_logging: False
 * /crazyflie_server/enable_parameters: True
 * /crazyflie_server/firmwareParams/ctrlMel/i_range_m_z: 1500
 * /crazyflie_server/firmwareParams/ctrlMel/i_range_xy: 2.0
 * /crazyflie_server/firmwareParams/ctrlMel/i_range_z: 0.4
 * /crazyflie_server/firmwareParams/ctrlMel/kR_xy: 70000
 * /crazyflie_server/firmwareParams/ctrlMel/kR_z: 60000
 * /crazyflie_server/firmwareParams/ctrlMel/kd_omega_rp: 200
 * /crazyflie_server/firmwareParams/ctrlMel/kd_xy: 0.2
 * /crazyflie_server/firmwareParams/ctrlMel/kd_z: 0.4
 * /crazyflie_server/firmwareParams/ctrlMel/ki_m_z: 500
 * /crazyflie_server/firmwareParams/ctrlMel/ki_xy: 0.05
 * /crazyflie_server/firmwareParams/ctrlMel/ki_z: 0.05
 * /crazyflie_server/firmwareParams/ctrlMel/kp_xy: 0.4
 * /crazyflie_server/firmwareParams/ctrlMel/kp_z: 1.25
 * /crazyflie_server/firmwareParams/ctrlMel/kw_xy: 20000
 * /crazyflie_server/firmwareParams/ctrlMel/kw_z: 12000
 * /crazyflie_server/firmwareParams/ctrlMel/mass: 0.032
 * /crazyflie_server/firmwareParams/ctrlMel/massThrust: 132000
 * /crazyflie_server/firmwareParams/flightmode/posCtrl: 1
 * /crazyflie_server/firmwareParams/ring/effect: 14
 * /crazyflie_server/firmwareParams/ring/headlightEnable: 0
 * /crazyflie_server/firmwareParams/ring/solidBlue: 20
 * /crazyflie_server/firmwareParams/ring/solidGreen: 0
 * /crazyflie_server/firmwareParams/ring/solidRed: 0
 * /crazyflie_server/force_no_cache: False
 * /crazyflie_server/genericLogTopicFrequencies: [10]
 * /crazyflie_server/genericLogTopic_log1_Variables: ['stabilizer.yaw'...
 * /crazyflie_server/genericLogTopics: ['log1']
 * /crazyflie_server/interactive_object: active-wand
 * /crazyflie_server/markerConfigurations/0/numPoints: 4
 * /crazyflie_server/markerConfigurations/0/offset: [0.0, -0.01, -0.04]
 * /crazyflie_server/markerConfigurations/0/points/0: [0.0177184, 0.013...
 * /crazyflie_server/markerConfigurations/0/points/1: [-0.0262914, 0.05...
 * /crazyflie_server/markerConfigurations/0/points/2: [-0.0328889, -0.0...
 * /crazyflie_server/markerConfigurations/0/points/3: [0.0431307, -0.03...
 * /crazyflie_server/motion_capture_type: optitrack
 * /crazyflie_server/numDynamicsConfigurations: 1
 * /crazyflie_server/numMarkerConfigurations: 1
 * /crazyflie_server/object_tracking_type: motionCapture
 * /crazyflie_server/optitrack_local_ip: 130.**.***.251
 * /crazyflie_server/optitrack_server_ip: 130.**.***.237
 * /crazyflie_server/print_latency: False
 * /crazyflie_server/save_point_clouds: ~/pointCloud.ot
 * /crazyflie_server/world_frame: /world
 * /crazyflie_server/write_csvs: False
 * /crazyflies: [{'initialPositio...
 * /joy/dev: /dev/input/js0
 * /rosdistro: kinetic
 * /rosversion: 1.12.12

NODES
  /
    crazyflie_manager (crazyflie_manager/crazyflie_manager)
    crazyflie_server (crazyflie_driver/crazyflie_server)
    joy (joy/joy_node)
    rqt (rqt_gui/rqt_gui)
    rqt_plot_yaw (rqt_plot/rqt_plot)
    rviz (rviz/rviz)

auto-starting new master
process[master]: started with pid [17130]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 02888ffe-0ec1-11e8-bc02-74d435137038
process[rosout-1]: started with pid [17143]
started core service [/rosout]
process[crazyflie_server-2]: started with pid [17160]
process[joy-3]: started with pid [17161]
process[crazyflie_manager-4]: started with pid [17162]
process[rviz-5]: started with pid [17175]
process[rqt-6]: started with pid [17193]
[ INFO] [1518308277.400331439]: Wait for services...
[ INFO] [1518308277.400980295]: waitForService: Service [/emergency] has not been advertised, waiting...
process[rqt_plot_yaw-7]: started with pid [17204]
[ INFO] [1518308277.422205284]: waitForService: Service [/emergency] is now available.
[ INFO] [1518308277.427002123]: Manager ready.
NatNetClient connecting: 130.**.***.251 to 130.**.***.237...
Could not bind socket. Error: 99
[ INFO] [1518308277.454497654]: Opened joystick: /dev/input/js0. deadzone_: 0.050000.
**[crazyflie_server-2] process has died [pid 17160, exit code 1, cmd /home/ubuntu/crazyswarm/ros_ws/devel/lib/crazyflie_driver/crazyflie_server __name:=crazyflie_server __log:=/home/ubuntu/.ros/log/02888ffe-0ec1-11e8-bc02-74d435137038/crazyflie_server-2.log].
log file: /home/ubuntu/.ros/log/02888ffe-0ec1-11e8-bc02-74d435137038/crazyflie_server-2*.log**
```

Thank you in advance.
