### ISSUE TITLE
Timeout error with chooser and hover_swarm.launch

### ISSUE THREAD

**Issue by andresbhoo** [USC-ACTLab/crazyswarm#79]
Hi whoenig,

Whenever I launch 'hover_swarm.launch' or 'chooser.py' I get a timeout error. I am able to connect to the crazyflie with the python3 client and it shows up with the tools scan, yet i am still getting this time out error. 
My crazyflie is at Address: 0xE7E7E7E7E7 and radio://0/81/2M. my allCrazyflies.yaml is as follows:

```
crazyflies:
  - id: 1
    channel: 81
    initialPosition: [.5, .4, 1.2]
    type: default
#  - id: 40
#    channel: 100
#    initialPosition: [-1.0, -0.5, 0.0]
#    type: default
```

crazyflies.yaml reads:

```
crazyflies:
- channel: 81
  id: 1
  initialPosition: [0.5, 0.4, 1.2]
  type: default
```

and the broadcast address in hover_swarm.launch is "FFE7E7E7E7".

The end of my 'hover_swarm.launch' output reads:

```
NODES
  /
    crazyswarm_server (crazyswarm/crazyswarm_server)
    crazyswarm_teleop (crazyswarm/crazyswarm_teleop)
    joy (joy/joy_node)
    rviz (rviz/rviz)

auto-starting new master
process[master]: started with pid [21179]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 177ac51e-8601-11e8-9c30-000c29022557
process[rosout-1]: started with pid [21192]
started core service [/rosout]
process[crazyswarm_server-2]: started with pid [21209]
process[joy-3]: started with pid [21210]
process[crazyswarm_teleop-4]: started with pid [21211]
process[rviz-5]: started with pid [21219]
[ INFO] [1531419988.943156177]: Wait for services...
[ INFO] [1531419988.946610439]: waitForService: Service [/emergency] has not been advertised, waiting...
[ INFO] [1531419988.974372646]: waitForService: Service [/emergency] is now available.
[ INFO] [1531419988.979788667]: Manager ready.
[ INFO] [1531419988.989793280]: Opened joystick: /dev/input/js0. deadzone_: 0.050000.
ch: 1
terminate called after throwing an instance of 'std::runtime_error'
  what():  timeout
[crazyswarm_server-2] process has died [pid 21209, exit code -6, cmd /home/cf/crazyswarm/ros_ws/devel/lib/crazyswarm/crazyswarm_server __name:=crazyswarm_server __log:=/home/cf/.ros/log/177ac51e-8601-11e8-9c30-000c29022557/crazyswarm_server-2.log].
log file: /home/cf/.ros/log/177ac51e-8601-11e8-9c30-000c29022557/crazyswarm_server-2*.log

```
Any suggestions? And thanks for the help!
